---
title: "IODS Final Assignment"
author: "Tuomas Tiihonen"
date: "10 joulukuuta 2017"
email: "tuomas.tiihonen@helsinki.fi"
abstract: This assignment tries to find underlying connections between variables in the student alcohol use dataset. The null hypothesis of the study, that no significant categories can be found in the data, was confirmed. No discernible categories could be identified using multiple correspondance analysis, but additional exploration of the data using first graphical tools and then logic regression showed that the education levels (secondary and higher contra lower) correlate between mothers and fathers of the students, and there is further correlation between the employment of the parents in the same sector.
output:
  html_document:
    theme: paper
    number_sections: true
    df_print: paged
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
    code_folding: hide
    toc_float:
      collapsed: false
      smooth_scroll: false
---

***
  
```{r child = "Ch-Introduction.Rmd"}
```
  
***
  
```{r child = "Ch-Initialisation.Rmd", echo=TRUE}
```

***
  
```{r child = "Ch-Exploration.Rmd", echo=TRUE}
```

***
```{r child = "Ch-Analysis.Rmd", echo=TRUE}
```

***
